server:
  port: 8090

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/graphql-spring-boot
    username: graphql-spring-boot
    password: graphql

  jpa:
    hibernate:
      ddl-auto: create

